#pragma once

#define CAPS_WORD_IDLE_TIMEOUT 8000
#define DYNAMIC_MACRO_KEEP_ORIGINAL_LAYER_STATE
#define LEADER_TIMEOUT 300
#define ONESHOT_TAP_TOGGLE 4
#define ONESHOT_TIMEOUT 5000
#define SPLIT_TRANSACTION_IDS_USER RPC_ID_USER_CAPS_WORD_SYNC
#define IND_MAX 50
